### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by tomgreenhill** [bootsz/mt-grid-backup#1]
Hey, 

I've setup the script according to the instructions, but somethings not going right! I'm not quite sure what the issue is, I thought it was a path issue, but still no joy...

Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /nfs/c03/h06/mnt/xxxxx/data/mt-grid-backup/src/s3upload.php on line 19 

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/php-5.6.21/share/pear') in /nfs/c03/h06/mnt/xxxxx/data/mt-grid-backup/src/s3upload.php on line 19 
S3 upload done. 

Any idea what's causing it please?

Thanks in advance, 
Tom

**Comment by maketimetodesign** [comment]
I figured it may be permissions, so looking in to that!

**Comment by tomgreenhill** [comment]
In case anyone else has an issue. The include path has to be absolute rather than relative as it's relative to the PEAR include path not the script location.
